name: Deploy to Render

on:
  push:
    branches: [ "main" ]  # Trigger on push to the "main" branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Replace with your Node.js version (e.g., 18, 20)

      # Step 3: Install dependencies and build (if needed)
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test  # Only if you have a test script in package.json

      # Step 5: Deploy to Render
      - name: Deploy to Render
        uses: render-actions/deploy@v1.1.0
        with:
          service-id: ${{ srv-cuku0ui3esus73b0cie0 }}
          api-key: ${{ rnd_50ropKLhOFDsU5aOJP4JyuzI1ipE }}
